### ISSUE TITLE
Provide tagged image version

### ISSUE THREAD

**Issue by marcust** [fhussonnois/docker-storm#11]
From the "latest" tag it is not always clear which version of storm is included in the actual docker image. Can you provide a tag for the included storm version as well. You have one for storm 0.9.4, but none for 0.9.5 yet.

**Comment by fhussonnois** [comment]
Thank you marcust, I have created tags. Is that ok for you if I close this issue ?

**Comment by marcust** [comment]
Thanks.
BTW, storm 0.9.6 is out ;)
