### ISSUE TITLE
specify a fixed ubuntu release

### ISSUE THREAD

**Issue by clescot** [fhussonnois/docker-storm#13]
hi,
i've got an issue when i build the Dockerfile .
here are  the output 
`Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.0.0_1.0.1-4ubuntu5.31_amd64.deb  404  Not Found `

`E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt-get upgrade -y' returned a non-zero code: 100`

when i switch from 'ubuntu:latest' to 'ubuntu:15.10', it works.

can you replace the ubuntu:latest with a fixed version in the Dockerfile?
best regards,

Charles.

**Comment by fhussonnois** [comment]
The base image has been fix to ubuntu:15.10
